### ISSUE TITLE
Spawnpoint integration with watchdog

### ISSUE THREAD

**Issue by gtfierro** [SoftwareDefinedBuildings/XBOS#11]

**Comment by jhkolb** [comment]
Keep an eye on https://github.com/immesys/spawnpoint/issues/16.

**Comment by jhkolb** [comment]
There is now a watchdog to monitor Bosswave connectivity of running containers. I also added this to the garber deployment. The watchdogs are under the prefix `410.bw2.garber`.

**Comment by immesys** [comment]
Can you do the other spawnpoints too? Thanks for this feature!

**Comment by jhkolb** [comment]
Sure, I just added `bw2mon` instances for the amplab and castle spawnpoints.

**Comment by gtfierro** [comment]
Looks good!
