### ISSUE TITLE
Verify autoRestart work

### ISSUE THREAD

**Issue by gtfierro** [SoftwareDefinedBuildings/XBOS#12]
Spawnpoints have been going down, and we're not quite sure the cause. Need to do some testing to make sure that autoRestart is working properly

- [ ] ensure deployed, problematic spawnpoints are up-to-date
- [ ] ensure deployed drivers have autoRestart in the configs

**Comment by jhkolb** [comment]
The issue with `spawnd` itself should now be resolved. We'll want to update deployed spawnpoints, and ensuring `autoRestart` on service configs also remains to be done.

**Comment by jhkolb** [comment]
The only potentially remaining issue is checking that all of our deployed drivers have auto-restart enabled. I believe all the drivers on Garber do.
