### ISSUE TITLE
Transition archiver to BTrDB v4

### ISSUE THREAD

**Issue by immesys** [SoftwareDefinedBuildings/XBOS#19]
There are numerous improvements to reliability, installability and performance in v4.

**Comment by gtfierro** [comment]
This should be very straightforward contingent on:
1) existence of Go bindings for BTrDBv4 (I'm guessing this is either done or very close)
2) migration plan from v3 -> v4 (this is the major one). Are the installations binary compatible, or do we need a re-ingester?

**Comment by immesys** [comment]
The bindings for v4 are done (gopkg.in/btrdb.v4)
migration from v3 to v4 is not done and not clear if we will make a generic one as opposed to site-specific ones.

**Comment by immesys** [comment]
Also no they are not binary compatible

**Comment by gtfierro** [comment]
First draft of this integration done in [pundat](https://github.com/gtfierro/pundat/commit/3f317eb70decc3083d76c685387b595aa1cb1ea2)

Waiting on getting a local installation of BTrDBv4 running, then the transition can complete

**Comment by gtfierro** [comment]
Done and deployed on the ucberkeley namespace

Worth keeping an eye on it to make sure it behaves correctly, but it seems to be behaving well so far
