### ISSUE TITLE
Develop Pelican Driver

### ISSUE THREAD

**Issue by gtfierro** [SoftwareDefinedBuildings/XBOS#25]

**Comment by jhkolb** [comment]
An initial of the Pelican driver is now finished. It's currently deployed as a container on the 410 testbed.

**Comment by gtfierro** [comment]
https://github.com/SoftwareDefinedBuildings/bw2-contrib/issues/8 then we can close this

**Comment by gtfierro** [comment]
Issue fixed in https://github.com/SoftwareDefinedBuildings/bw2-contrib/pull/9
