### ISSUE TITLE
Standardize Enphase Driver

### ISSUE THREAD

**Issue by gtfierro** [SoftwareDefinedBuildings/XBOS#4]

**Comment by peterxu30** [comment]
Update in pull request.

**Comment by gtfierro** [comment]
Done as of https://github.com/SoftwareDefinedBuildings/bw2-contrib/commit/1f8c62fb59099f792a96db1a7e4587bfc777e579 and https://github.com/SoftwareDefinedBuildings/bw2-contrib/commit/024f78e3864741c3a11bc0344fb4dd19ee35f7e3
