### ISSUE TITLE
MDAL RAW output to dataframe

### ISSUE THREAD

**Issue by marcopritoni** [SoftwareDefinedBuildings/XBOS#55]
MDAL returns a pandas dataframe UNLESS the "Selectors": [mdal.RAW]. In that case it returns a dict. For consistency I would prefer to have an aligned DF in both cases. I understand that the second one may have a lot of NaN.

**Comment by gtfierro** [comment]
TODO:

- [ ] Fix https://docs.xbos.io/mdal.html#using documentation

**Comment by gtfierro** [comment]
https://github.com/SoftwareDefinedBuildings/XBOS/pull/59 should fix this. Can you  update your XBOS python bindings to 0.0.29 and give it a try?
