### ISSUE TITLE
historic weather data has unexpected 32 degrees data for Nan values in weather.gov

### ISSUE THREAD

**Issue by daniellengyel** [SoftwareDefinedBuildings/XBOS#65]
When querying MDAL for weather data for weather station _weather_KTLC1_temperature_ with uuid _c3d0f042-2cb7-387c-8867-4190fef4fd2c_ it results in unexpected 32 values for some times (e.g. at time 2018-06-03 06:50 UTC).

While examining weather.gov such values align with times when weather.gov has NULL values such as seen in the screenshot attached. 

<img width="842" alt="screen shot 2018-06-03 at 22 12 06" src="https://user-images.githubusercontent.com/13992716/41138239-be1c76c0-6a94-11e8-8234-8d218998aaf6.png">

**Comment by gtfierro** [comment]
https://github.com/SoftwareDefinedBuildings/bw2-contrib/pull/33

**Comment by gtfierro** [comment]
This should be fixed going forward, but its difficult to fix the historical data.
